### ISSUE TITLE
Support Debian packages

### ISSUE THREAD

**Issue by camelpunch** [camelpunch/bintray-resource#3]
Example config:

``` yaml
      params:
        file: output/plugins/plugins/*/gen_smtp-*.ez
        deb:
          distribution:
            - wheezy
            - jessie
          component:
            - main
          architecture:
            - i386
            - amd64
```
